/// Flutter icons Caticons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Caticons
///      fonts:
///       - asset: fonts/Caticons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Caticons {
  Caticons._();

  static const _kFontFam = 'Caticons';
  static const String _kFontPkg = null;

  static const IconData settings = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_border = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_fruits_and_vegetables_64 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_vegetables_60__1_ = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_hot_1868720 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_ionic_md_heart_empty = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_drink_1827718 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat__1_ = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hen = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken__3_ = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken__4_ = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_vegetables_60 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calender = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guest = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabels = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vegetable = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruits_and_vegetables__1_ = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruits_and_vegetables = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData booking = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_1 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fav = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
